id: I461EEC01
ocr_import_info:
  timestamp: '2023-08-15T02:12:35.544948+00:00'
  batch_id: batch-675f
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-15 02:50:49.049024+00:00
last_modified: 2023-08-15 02:50:49.049033+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W27521
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27521
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་ཀྱི་དབྱིངས་སུ་བསྟོད་པའི་འགྲེལ་པ་ངེས་དོན་ཟབ་མོའི་གཏེར་གྱི་ཁ་འབྱེད།
  languages:
  - bo
  author: བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.960450131899532
  ocr_word_median_confidence_index: 0.997778535
bases:
  I4389:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4389
      total_pages: 280
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4389.txt
    statistics:
      ocr_word_median_confidence_index: 0.997778535
      ocr_word_mean_confidence_index: 0.960450131899532
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
